width=1920
height=1080

work_threads = 12
display = off
pause_when_done = off

; NB #moves := 2 ^ NumStones - 1.
;declare = NumStones=5
;declare = FramesPerMove=20

cyclic_animation = on
; NB  #moves * #frames-per-move
;final_frame = 620

antialias = on
sampling_method = 3
antialias_threshold = 0.01
antialias_confidence = 0.9995
antialias_gamma = 1
jitter = off
quality = 11

input_file_name = hanoi.pov

all_file = on
file_gamma = sRGB
output_file_name = hanoi_
